export const NATIONAL_FLAG: Record<string, string> = {
  USA: 'bg-us',
  KOR: 'bg-kr',
  FRN: 'bg-fr',
  ITA: 'bg-it',
  CHI: 'bg-cn',
  GER: 'bg-gm',
  JPA: 'bg-jp',
  POR: 'bg-pt',
  SPN: 'bg-es',
  CAN: 'bg-ca',
  ENG: 'bg-uk',
  AUS: 'bg-au',
  NZL: 'bg-nz',
  PHL: 'bg-ph',
  ZAF: 'bg-za',
};
